name: otraku
description: An unofficial AniList app.

publish_to: 'none'

version: 1.2.3+55

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management.
  flutter_riverpod: ^2.3.2

  # Data fetching.
  http: ^0.13.5

  # Settings storage.
  hive: ^2.2.3

  # Access to device storage. Used for [hive] setup.
  path_provider: ^2.0.14

  # Secure storage for the access tokens.
  flutter_secure_storage: ^8.0.0

  # Used for configuring [cached_network_image], which already imports it.
  flutter_cache_manager: ^3.3.0

  # Image caching.
  cached_network_image: ^3.2.3

  # Opening links in the browser.
  url_launcher: ^6.1.10

  # Flutter deep linking didn't handle url fragments before. When [go_router] is implemented, this can be removed.
  app_links: ^3.4.2

  # Access to platform theme and easy theme interpolation.
  dynamic_color: ^1.6.2

  # Background tasks for notification fetching.
  workmanager: ^0.5.1

  # Sending device notifications.
  flutter_local_notifications: ^13.0.0

  # Translating html into flutter widgets.
  flutter_widget_from_html_core: ^0.10.0

  # An addition to the material icons.
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/ios.png"
  adaptive_icon_background: "#0D161E"
  adaptive_icon_foreground: "assets/icons/android.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/about.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic