name: otraku
description: An unofficial AniList app.

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.1.1
  get_storage: ^2.0.1
  http: ^0.13.1
  url_launcher: ^6.0.3
  app_links: ^2.0.0
  flutter_widget_from_html_core: ^0.6.0-rc.2021031201
  flutter_secure_storage: ^4.1.0
  fluentui_system_icons: ^1.1.112

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/ios_r.png"
  adaptive_icon_background: "#0F171E"
  adaptive_icon_foreground: "assets/icons/android_b.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/about_icon.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500